version: '3.8'

services:
  app:
    image: your-dockerhub-username/nest-api:latest
    container_name: nest-api-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
    depends_on:
      - mysql
      - redis
    networks:
      - nest-network
    volumes:
      - ./logs:/app/logs

  mysql:
    image: mysql:8.0
    container_name: nest-api-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - nest-network

  redis:
    image: redis:7-alpine
    container_name: nest-api-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nest-network
    command: redis-server --appendonly yes

  nginx:
    image: nginx:alpine
    container_name: nest-api-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - nest-network

volumes:
  mysql_data:
  redis_data:

networks:
  nest-network:
    driver: bridge 